---
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:3.2.0
    network_mode: host
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:3.2.0
    network_mode: host
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:32181
      # IP_ACCESSIBLE_FROM_DOCKER_HOST: see `.env` file in this directory for explanations
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${IP_ACCESSIBLE_FROM_DOCKER_HOST}:29092

  schema-registry:
    image: confluentinc/cp-schema-registry:3.2.0
    network_mode: host
    depends_on:
      - zookeeper
      - kafka
    ports:
      - '8081'
    environment:
      SCHEMA_REGISTRY_HOST_NAME: localhost
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: localhost:32181

  kafka-streams-examples:
    image: confluentinc/cp-kafka-streams-examples:3.2.0
    network_mode: host
    depends_on:
      - kafka
      - schema-registry
    ports:
      - '7070'
    environment:
      STREAMS_BOOTSTRAP_SERVERS: localhost:29092
      STREAMS_SCHEMA_REGISTRY_HOST: localhost
      STREAMS_SCHEMA_REGISTRY_PORT: 8081
      KAFKA_MUSIC_APP_REST_HOST: localhost
      KAFKA_MUSIC_APP_REST_PORT: 7070
